<?xml version="1.0" encoding="UTF-8"?>
<!--
  forge-member：普通用户账号、注册登录与用户端接口，依赖基础模块。
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.orangenode</groupId>
        <artifactId>forge-backend</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>forge-member</artifactId>
    <name>forge-member</name>
    <description>普通用户模块</description>

    <dependencies>
        <dependency>
            <groupId>cn.orangenode</groupId>
            <artifactId>forge-framework</artifactId>
        </dependency>
    </dependencies>
</project>
